variables:
  DOCKER_DRIVER: overlay

# This file is a template, and might need editing before it works on your project.
docker-build:
  # Official docker image.
  image: gitlab/dind:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  tags:
    - main
  only:
    - "master"

deploy:
  stage: deploy
  image: gitlab/dind:latest

  before_script:
    - apt-get update -qq
  script:
    - echo "$DEPLOY_SERVER_PRIVATE_KEY" > dkey
    - chmod 700 dkey
    - ssh -o StrictHostKeyChecking=no -i dkey root@$DEPLOYMENT_SERVER_IP "cd minute-of-fame; git checkout "$CI_COMMIT_BRANCH"; git pull; git docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}; docker-compose -f docker-compose.yml stop; docker-compose -f docker-compose.yml rm web; docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"; docker-compose -f docker-compose.yml up -d"
  tags:
    - main
  only:
    - "master"