version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    hostname: db
    ports:
      - 5432:5432
    networks:
      - main
    volumes:
    - ./db_data:/var/lib/postgresql/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main

  kurento:
    image: kurento/kurento-media-server
    ports:
      - 8888:8888
    volumes:
      - ./recs:/recs

networks:
  main: