version: '3'
services:
  web:
    image: maplegend/minute-of-fame
    build: .
    command: /bin/sh -c "python manage.py migrate && python manage.py createcachetable && daphne -b 0.0.0.0 -p 80 minute_of_fame.asgi:application"
    env_file:
      - ./web.env
      - ./db.env
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - RHOST=redis
    networks:
      - main
    depends_on:
      - redis
      - db
      - multi_connection

  multi_connection:
    image: maplegend/multi_connection:master
    command: node server --port 9001
    networks:
      - main
    ports:
      - 9001:9001

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - main

  db:
    env_file:
      - ./db.env
    image: postgres
    restart: always
    hostname: db
    networks:
      - main

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - main

networks:
  main:
