version: '3'

services:
  web:
    image: maplegend/minute-of-fame
    build: .
    command: daphne -b 0.0.0.0 -p 80 minute_of_fame.asgi:application
    volumes:
      - .:/code
    ports:
      - "80:80"