# Generated by Django 3.0.3 on 2020-02-20 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('multi_account', models.BooleanField(default=False)),
                ('offensive', models.BooleanField(default=False)),
                ('inappropriate_video_content', models.BooleanField(default=False)),
                ('additional_information', models.CharField(max_length=250)),
                ('badass_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='badass_id', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='sender_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
