# Generated by Django 3.0.4 on 2020-04-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200404_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollstat',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='streamview',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
