# Generated by Django 3.0.4 on 2020-04-08 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20200405_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('Vk', models.CharField(max_length=60)),
                ('instagram', models.CharField(max_length=60)),
                ('facebook', models.CharField(max_length=60)),
                ('twitter', models.CharField(max_length=60)),
                ('odnoklassniki', models.CharField(max_length=60)),
                ('youtube_play', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
