# Generated by Django 3.0.3 on 2020-02-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200229_1354'),
        ('app', '0004_auto_20200227_1911'),
    ]

    operations = [
    ]
