# Generated by Django 3.0.4 on 2020-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='title',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
