# Generated by Django 3.0.3 on 2020-03-07 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_merge_20200229_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pollstat',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='pollstat',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pollstat',
            name='poll_result',
        ),
        migrations.AddField(
            model_name='pollstat',
            name='year_in_school',
            field=models.IntegerField(choices=[(0, 'Dislike'), (1, 'Like')], default=1),
        ),
        migrations.CreateModel(
            name='StreamView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pollstat',
            name='stream',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Stream'),
            preserve_default=False,
        ),
    ]
