# Generated by Django 3.0.3 on 2020-03-07 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20200307_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollstat',
            old_name='year_in_school',
            new_name='vote',
        ),
        migrations.AddField(
            model_name='pollstat',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
